Added js_doc overview info about plugin. [CHAT]
pubnub/chat-engine-open-graph pull request #5
Opened 2018-10-04 21:49 UTC by crgbaumgart

2018-10-05 19:42 UTC, ianjennings requested changes

2018-10-05 19:42 UTC, ianjennings commented on src/plugin.js
> +* @overview ChatEngine Open Graph unfurls URLs sent in chat messages and transforms them into more interactive pieces of media. More info [here](https://www.pubnub.com/blog/open-graph-plugin-chatengi
There's a tag called "@see" where you can add links like this. http://usejsdoc.org/tags-see.html

2018-10-05 19:42 UTC, ianjennings commented on src/plugin.js
> +* @requires {@link ChatEngine}
I don't think other plugins have this? Is JSDOC smart enough for this?

2018-10-05 19:45 UTC, ianjennings commented on src/plugin.js
> +* @requires {@link ChatEngine}
If this works, all plugins should have it (or none).

2019-03-08 00:36 UTC, MessagingMoore approved these changes

2019-03-08 00:36 UTC, merged